# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
defaultContentLanguage = "zh-Hans"
baseURL = "https://semitia.top/"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

# [params]
#   # ... 其他配置 ...
  
#   # 在这里引入你的 custom.css
#   customCSS = ["css/custom.css"]