languageCode = "zh-Hans"
languageName = "简体中文"
languageDirection = "ltr"
weight = 2

title = "Semitia-Blog"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2006年1月2日"
  mainSections = ["posts", "essays", "notes"]
  # description = "一款基于Tailwindcss的强大且轻量的Hugo主题"

[params.author]
  name = "Semitia"
  image = "img/Citlali-avator.jpg"
  headline = "于群峰之上，更觉长风浩荡。"
  bio = "机器人小白。"
  links = [
    # { x-twitter = "https://twitter.com/" },
    # { facebook = "https://facebook.com/" },
    # { linkedin = "https://linkedin.com/" },
    { tools = "https://tools.semitia.top/"},
    { games = "https://games.semitia.top/"},
    # { youtube = "https://youtube.com/" },
    { github = "https://github.com/" },
    { google-scholar = "https://scholar.google.com/" },
    { email = "mailto:Alexavier-L@outlook.com"},
    
    # { bilibili = "https://bilibili.com/" },
  ]
