languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "Semitia-Blog"
copyright = "&copy; 2024 Congo contributors"

[params]
  dateFormat = "2 January 2006"
  mainSections = ["posts", "essays", "notes"]
  # description = "一款基于Tailwindcss的强大且轻量的Hugo主题"

[params.author]
  name = "Semitia"
  image = "img/Citlali-avator.jpg"
  headline = "A Robot newbie."
  bio = "A Robot newbie."
  links = [
    # { x-twitter = "https://twitter.com/" },
    # { facebook = "https://facebook.com/" },
    # { linkedin = "https://linkedin.com/" },
    { tools = "https://tools.semitia.top/"},
    { games = "https://games.semitia.top/"},
    { christmas = "https://christmas.semitia.top/"},
    # { youtube = "https://youtube.com/" },
    { github = "https://github.com/" },
    { google-scholar = "https://scholar.google.com/" },
    { email = "mailto:Alexavier-L@outlook.com"},
    
    # { bilibili = "https://bilibili.com/" },
  ]
